name: flutter_base_project_mvvm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.2
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1
  fluttertoast: ^8.2.8
  equatable: ^2.0.5
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
      - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
      - asset: assets/fonts/Inter_18pt-Light.ttf
      - asset: assets/fonts/Inter_18pt-Medium.ttf
      - asset: assets/fonts/Inter_18pt-Regular.ttf
      - asset: assets/fonts/Inter_18pt-Bold.ttf
      - asset: assets/fonts/Inter_18pt-SemiBold.ttf
      - asset: assets/fonts/Inter_18pt-ExtraBold.ttf


